# Phase 7: Autonomous AI Agents & Orchestration Configuration
# Complete configuration for all Phase 7 components

# Autonomous Agent Architecture Configuration
agent_architecture:
  orchestrator:
    max_agents: 100
    agent_types:
      - COORDINATOR
      - TASK_EXECUTOR
      - MONITOR
      - ANALYZER
      - SWARM_MEMBER
    default_capabilities:
      - COMMUNICATION
      - TASK_EXECUTION
      - STATUS_REPORTING
    heartbeat_interval: 30  # seconds
    agent_timeout: 300  # seconds
  
  agent_defaults:
    max_concurrent_tasks: 5
    memory_limit: "512MB"
    cpu_limit: 1.0
    auto_restart: true
    logging_level: INFO

# Multi-Agent Coordination Configuration
coordination:
  strategies:
    contract_net:
      enabled: true
      bid_timeout: 10  # seconds
      max_bids_per_task: 10
      selection_criteria: "best_capability_match"
    
    auction_based:
      enabled: true
      auction_rounds: 3
      reserve_price: 0.5
      bid_increment: 0.1
    
    consensus:
      enabled: true
      min_participants: 3
      consensus_threshold: 0.66
      voting_timeout: 30  # seconds
  
  load_balancing:
    algorithm: "weighted_round_robin"
    rebalance_interval: 60  # seconds
    max_load_difference: 0.3

# Agent Communication Protocols Configuration
communication:
  protocols:
    direct_message:
      enabled: true
      max_message_size: "10MB"
      encryption: true
      delivery_guarantee: "at_least_once"
    
    broadcast:
      enabled: true
      max_recipients: 1000
      ttl: 60  # seconds
    
    publish_subscribe:
      enabled: true
      max_topics: 100
      max_subscribers_per_topic: 500
      message_retention: 3600  # seconds
    
    request_response:
      enabled: true
      default_timeout: 30  # seconds
      max_retries: 3
    
    gossip:
      enabled: true
      fanout: 3
      rounds: 5
      interval: 10  # seconds
  
  message_queue:
    max_queue_size: 10000
    priority_levels: 4
    dead_letter_queue: true
    message_ttl: 3600  # seconds

# Task Planning & Execution Configuration
task_planning:
  strategies:
    hierarchical:
      enabled: true
      max_decomposition_depth: 5
      min_task_granularity: "1 minute"
    
    reactive:
      enabled: true
      reaction_time: 100  # milliseconds
      adaptation_threshold: 0.3
    
    goal_oriented:
      enabled: true
      goal_evaluation_interval: 30  # seconds
      max_goals_per_agent: 10
    
    hybrid:
      enabled: true
      strategy_weights:
        hierarchical: 0.4
        reactive: 0.3
        goal_oriented: 0.3
  
  execution:
    modes:
      - SEQUENTIAL
      - PARALLEL
      - DISTRIBUTED
    default_mode: PARALLEL
    max_parallel_tasks: 20
    task_timeout: 600  # seconds
    checkpoint_interval: 60  # seconds

# Swarm Intelligence Configuration
swarm_intelligence:
  algorithms:
    particle_swarm:
      enabled: true
      num_particles: 50
      max_iterations: 1000
      inertia_weight: 0.7
      cognitive_weight: 1.5
      social_weight: 1.5
      velocity_limit: 1.0
    
    ant_colony:
      enabled: true
      num_ants: 30
      pheromone_evaporation: 0.1
      pheromone_deposit: 1.0
      alpha: 1.0  # pheromone importance
      beta: 2.0   # heuristic importance
    
    bee_colony:
      enabled: true
      num_scouts: 10
      num_workers: 20
      num_onlookers: 20
      abandonment_limit: 10
      search_radius: 0.1
  
  optimization:
    convergence_threshold: 0.001
    stagnation_limit: 100
    diversity_maintenance: true
    elite_preservation: 0.1

# Agent Learning & Adaptation Configuration
learning_adaptation:
  strategies:
    q_learning:
      enabled: true
      learning_rate: 0.1
      discount_factor: 0.95
      epsilon: 0.1
      epsilon_decay: 0.995
      min_epsilon: 0.01
    
    policy_gradient:
      enabled: true
      learning_rate: 0.001
      entropy_coefficient: 0.01
      value_coefficient: 0.5
      max_grad_norm: 0.5
    
    transfer_learning:
      enabled: true
      knowledge_retention: 0.8
      adaptation_rate: 0.2
      domain_similarity_threshold: 0.7
  
  experience_replay:
    buffer_size: 10000
    batch_size: 32
    prioritized: true
    alpha: 0.6  # prioritization
    beta: 0.4   # importance sampling
  
  knowledge_base:
    max_entries: 100000
    compression: true
    indexing: "vector"
    similarity_metric: "cosine"

# Production ML Libraries Configuration
ml_libraries:
  tensorflow:
    enabled: true
    version: ">=2.0.0"
    gpu_support: true
    mixed_precision: true
    xla_optimization: true
    distribute_strategy: "mirrored"
  
  pytorch:
    enabled: true
    version: ">=2.0.0"
    cuda_enabled: true
    cudnn_benchmark: true
    num_workers: 4
    pin_memory: true
  
  sklearn:
    enabled: true
    version: ">=1.0.0"
    n_jobs: -1  # use all cores
    random_state: 42
  
  model_serving:
    format: "onnx"
    quantization: "dynamic"
    batching: true
    max_batch_size: 32
    timeout: 1000  # milliseconds

# Distributed Messaging Configuration
messaging:
  redis:
    enabled: true
    host: "localhost"
    port: 6379
    db: 0
    password: null
    connection_pool_size: 10
    socket_timeout: 5
    retry_on_timeout: true
  
  rabbitmq:
    enabled: true
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    virtual_host: "/"
    heartbeat: 600
    connection_attempts: 3
    retry_delay: 2
  
  kafka:
    enabled: false
    bootstrap_servers: "localhost:9092"
    client_id: "archon_agent"
    group_id: "archon_agents"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    max_poll_records: 500
  
  fallback:
    use_in_memory: true
    persist_to_disk: true
    max_memory_usage: "1GB"

# Real Environment Interfaces Configuration
environment_interfaces:
  file_system:
    enabled: true
    watch_directories:
      - "/mnt/c/Jarvis/AI Workspace/Archon"
    file_patterns:
      - "*.py"
      - "*.yaml"
      - "*.json"
    max_file_size: "100MB"
    scan_interval: 30  # seconds
  
  web_services:
    enabled: true
    max_concurrent_requests: 10
    timeout: 30  # seconds
    retry_attempts: 3
    rate_limit: 100  # requests per minute
    user_agent: "Archon/1.0"
  
  databases:
    postgresql:
      enabled: true
      connection_pool_size: 5
      statement_timeout: 30000  # milliseconds
    
    mongodb:
      enabled: false
      connection_string: "mongodb://localhost:27017"
      database: "archon"
    
    redis:
      enabled: true
      use_connection_pool: true
  
  iot_sensors:
    enabled: false
    protocols:
      - MQTT
      - CoAP
      - WebSocket
    polling_interval: 1000  # milliseconds
    buffer_size: 1000

# Performance Optimization Configuration
performance:
  gpu_acceleration:
    enabled: true
    cuda:
      enabled: true
      device_id: 0
      memory_fraction: 0.8
      allow_growth: true
    
    opencl:
      enabled: false
      platform_id: 0
      device_id: 0
  
  cpu_optimization:
    num_threads: 8
    thread_pool: "default"
    vectorization: true
    simd: true
    numa_aware: false
  
  memory_optimization:
    object_pooling: true
    pool_size: 1000
    garbage_collection:
      strategy: "generational"
      threshold: 0.8
    cache:
      type: "lru"
      size: 10000
      ttl: 3600  # seconds
  
  parallel_processing:
    max_workers: 16
    chunk_size: 1000
    backend: "multiprocessing"
    start_method: "spawn"

# Monitoring & Metrics Configuration
monitoring:
  metrics:
    enabled: true
    collection_interval: 10  # seconds
    retention_period: 86400  # seconds (1 day)
    export_format: "prometheus"
  
  logging:
    level: INFO
    format: "json"
    max_file_size: "100MB"
    max_backups: 10
    compression: true
  
  tracing:
    enabled: true
    sampling_rate: 0.1
    export_endpoint: "http://localhost:4317"
  
  health_checks:
    enabled: true
    interval: 30  # seconds
    timeout: 5  # seconds
    failure_threshold: 3

# Security Configuration
security:
  authentication:
    enabled: true
    method: "jwt"
    token_expiry: 3600  # seconds
    refresh_token_expiry: 86400  # seconds
  
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_interval: 86400  # seconds
  
  authorization:
    enabled: true
    rbac: true
    default_role: "agent"
    admin_roles:
      - "orchestrator"
      - "admin"
  
  audit:
    enabled: true
    log_all_operations: false
    sensitive_data_masking: true

# Deployment Configuration
deployment:
  environment: "development"  # development, staging, production
  
  docker:
    base_image: "python:3.12-slim"
    registry: "localhost:5000"
    namespace: "archon"
    
  kubernetes:
    enabled: false
    namespace: "archon-agents"
    replica_count: 3
    resource_limits:
      cpu: "2"
      memory: "4Gi"
    resource_requests:
      cpu: "500m"
      memory: "1Gi"
  
  scaling:
    auto_scaling: true
    min_replicas: 2
    max_replicas: 10
    target_cpu_utilization: 70
    target_memory_utilization: 80

# Feature Flags
feature_flags:
  enable_autonomous_agents: true
  enable_swarm_intelligence: true
  enable_distributed_messaging: true
  enable_gpu_acceleration: true
  enable_production_ml: true
  enable_real_environment: true
  enable_performance_optimization: true
  experimental_features: false

# Version Information
version:
  phase: 7
  name: "Autonomous AI Agents & Orchestration"
  release: "1.0.0"
  api_version: "v1"
  last_updated: "2024-12-30"